apiVersion: v1
kind: Pod
metadata:
  name: sample-kubectl
spec:
  serviceAccountName: sample-serviceaccount
  containers:
  - name: kubectl-container
    image: lanchlanevenson/k8s-kubectl:v1.18.2
    command: ["sleep", "86400"]
