apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restored-pvc
spec:
  storageClassName: sample-csi-storageclass
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  dataSource:
    kind: VolumeSnapshot
    name: source-pvc-snapshot
    apiGroup: snapshot.storage.k8s.io
