apiVersion: v1
kind: Pod
metadata:
  name: sample-emptydir-limit
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
    volumeMounts:
    - name: cache-volume
      mountPath: /cache
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 128Mi
