apiVersion: v1
kind: Pod
metadata:
  name: sample-hostaliases
  labels:
    name: myapp
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
  hostAliases:
  - ip: 8.8.8.8
    hostnames:
      - google-dns
      - google-public-dns