apiVersion: v1
kind: Pod
metadata:
  name: sample-capabilities
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
        drop:
        - AUDIT_WRITE
